# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18o7sfRxIvR1zY8etQ0j041tuD0e3sc4s
"""

!pip install datasets

import json
from datasets import load_dataset

# Default system prompt for the assistant
DEFAULT_SYSTEM_PROMPT = "You are customer support. You are a helpful and kind AI assistant."

def create_dataset(question, answer):
    return {
        "messages": [
            {"role": "system", "content": DEFAULT_SYSTEM_PROMPT},
            {"role": "user", "content": question},
            {"role": "assistant", "content": answer},
        ]
    }

# Load the customer support responses dataset
dataset = load_dataset("Kaludi/Customer-Support-Responses")

# Write the dialogue datasets to a JSON Lines file
with open("data.jsonl", "w") as f:
    for example in dataset['train']:
        question = example['query']
        answer = example['response']
        f.write(json.dumps(create_dataset(question, answer)) + "\n")